[package]
name = "annict-card"
# description = ""
version = "0.0.1"
authors = ["Nep <spica@starry.blue>"]
edition = "2018"
license = "MIT"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
graphql_client = "0.9"
serde = "1.0"
reqwest = { version = "0.11", features = ["json"] }
envy = "0.4"
env_logger = "0.8"
log = "0.4"
