name: 'Check'

on:
  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  build:
    uses: SlashNephy/.github/.github/workflows/cargo-run.yml@master
    permissions:
      contents: 'read'
    with:
      command: 'build'
      args: '--release'
